language: node_js

sudo: false

node_js:
  - "4.2.1"

after_success:
  - |
      curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/andreyderma/testingndeploying/trigger/23614b89-531c-4756-8343-7d119b479194/
